[2022-12-31T22:50:32.552+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.test manual__2022-12-31T22:50:28.182854+00:00 [queued]>
[2022-12-31T22:50:32.597+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.test manual__2022-12-31T22:50:28.182854+00:00 [queued]>
[2022-12-31T22:50:32.599+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-31T22:50:32.601+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-31T22:50:32.602+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-31T22:50:32.672+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): test> on 2022-12-31 22:50:28.182854+00:00
[2022-12-31T22:50:32.692+0000] {standard_task_runner.py:55} INFO - Started process 62 to run task
[2022-12-31T22:50:32.720+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'test', 'manual__2022-12-31T22:50:28.182854+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpmcbce13f']
[2022-12-31T22:50:32.730+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask test
[2022-12-31T22:50:33.104+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.test manual__2022-12-31T22:50:28.182854+00:00 [running]> on host 6bd76effbc07
[2022-12-31T22:50:33.557+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-31T22:50:28.182854+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-31T22:50:28.182854+00:00
[2022-12-31T22:50:33.620+0000] {base.py:71} INFO - Using connection ID 'mongodb' for task execution.
[2022-12-31T22:50:33.653+0000] {base.py:71} INFO - Using connection ID 'mongodb' for task execution.
[2022-12-31T22:50:33.950+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 27, in print_
    extract.execute()
TypeError: execute() missing 1 required positional argument: 'context'
[2022-12-31T22:50:33.993+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dpt_cosmetic, task_id=test, execution_date=20221231T225028, start_date=20221231T225032, end_date=20221231T225033
[2022-12-31T22:50:34.057+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task test (execute() missing 1 required positional argument: 'context'; 62)
[2022-12-31T22:50:34.094+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-31T22:50:34.211+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
