[2023-01-07T01:57:11.574+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T01:57:11.815+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T01:57:11.822+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T01:57:11.828+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T01:57:11.830+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T01:57:12.078+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): private_info.transform> on 2023-01-06 00:00:00+00:00
[2023-01-07T01:57:12.133+0000] {standard_task_runner.py:55} INFO - Started process 121 to run task
[2023-01-07T01:57:12.212+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'private_info.transform', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '476', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpyjlmazec']
[2023-01-07T01:57:12.228+0000] {standard_task_runner.py:83} INFO - Job 476: Subtask private_info.transform
[2023-01-07T01:57:12.440+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T01:57:13.935+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T01:57:14.929+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=private_info.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T01:57:14.984+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-07T01:57:14.995+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 1']
[2023-01-07T01:57:15.214+0000] {subprocess.py:86} INFO - Output:
[2023-01-07T01:57:16.311+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-01-07T01:57:16.680+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=private_info.transform, execution_date=20230106T000000, start_date=20230107T015711, end_date=20230107T015716
[2023-01-07T01:57:17.021+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T01:57:19.732+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-07T05:16:31.581+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:16:32.093+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:16:32.100+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:16:32.134+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T05:16:32.136+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:16:33.222+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): private_info.transform> on 2023-01-06 00:00:00+00:00
[2023-01-07T05:16:33.527+0000] {standard_task_runner.py:55} INFO - Started process 425 to run task
[2023-01-07T05:16:33.792+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'private_info.transform', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '563', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpe0egh5v_']
[2023-01-07T05:16:34.178+0000] {standard_task_runner.py:83} INFO - Job 563: Subtask private_info.transform
[2023-01-07T05:16:47.150+0000] {cli_action_loggers.py:125} WARNING - Failed to log action with (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-01-07T05:16:53.916+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T05:16:52.753+0000] {base_job.py:232} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 204, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2961, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3039, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2775, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2878, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-01-07T05:18:03.912+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T05:18:08.572+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=private_info.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T05:18:08.640+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-07T05:18:08.651+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 1']
[2023-01-07T05:18:08.741+0000] {subprocess.py:86} INFO - Output:
[2023-01-07T05:18:09.782+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-01-07T05:18:10.156+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=private_info.transform, execution_date=20230106T000000, start_date=20230107T051631, end_date=20230107T051810
[2023-01-07T05:18:10.599+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T05:18:12.114+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-07T05:32:15.548+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:32:15.879+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:32:15.893+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:32:15.894+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T05:32:15.896+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:32:16.206+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): private_info.transform> on 2023-01-06 00:00:00+00:00
[2023-01-07T05:32:16.305+0000] {standard_task_runner.py:55} INFO - Started process 90 to run task
[2023-01-07T05:32:16.348+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'private_info.transform', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '612', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8oc5a1pp']
[2023-01-07T05:32:16.394+0000] {standard_task_runner.py:83} INFO - Job 612: Subtask private_info.transform
[2023-01-07T05:32:16.610+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T05:32:17.201+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.private_info.transform scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T05:32:18.117+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=private_info.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T05:32:18.136+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-07T05:32:18.142+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 1']
[2023-01-07T05:32:18.275+0000] {subprocess.py:86} INFO - Output:
[2023-01-07T05:32:19.297+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-01-07T05:32:19.550+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=private_info.transform, execution_date=20230106T000000, start_date=20230107T053215, end_date=20230107T053219
[2023-01-07T05:32:20.636+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T05:32:21.846+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
