[2023-01-07T01:58:16.649+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction_01.insert_data scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T01:58:16.712+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction_01.insert_data scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T01:58:16.713+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T01:58:16.715+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T01:58:16.716+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T01:58:16.822+0000] {taskinstance.py:1383} INFO - Executing <Task(GCSToBigQueryOperator): transaction_01.insert_data> on 2023-01-06 00:00:00+00:00
[2023-01-07T01:58:16.838+0000] {standard_task_runner.py:55} INFO - Started process 235 to run task
[2023-01-07T01:58:16.853+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'transaction_01.insert_data', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '508', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp070l5mnh']
[2023-01-07T01:58:16.861+0000] {standard_task_runner.py:83} INFO - Job 508: Subtask transaction_01.insert_data
[2023-01-07T01:58:16.909+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T01:58:17.146+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.transaction_01.insert_data scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T01:58:17.512+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=transaction_01.insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T01:58:17.516+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-07T01:58:17.548+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-07T01:58:17.553+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-07T01:58:17.576+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-07T01:58:18.288+0000] {bigquery.py:2842} INFO - Project not included in destination_project_dataset_table: cosmetic.transaction; using project "my-kubeflow-370515"
[2023-01-07T01:58:18.292+0000] {bigquery.py:1554} INFO - Inserting job ***_1673056698291014_647f5439a545c01af290f107921986eb
[2023-01-07T01:58:24.591+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=transaction_01.insert_data, execution_date=20230106T000000, start_date=20230107T015816, end_date=20230107T015824
[2023-01-07T01:58:24.704+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T01:58:24.859+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-07T05:33:29.138+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction_01.insert_data scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:33:29.228+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction_01.insert_data scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:33:29.229+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:33:29.231+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T05:33:29.232+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:33:29.645+0000] {taskinstance.py:1383} INFO - Executing <Task(GCSToBigQueryOperator): transaction_01.insert_data> on 2023-01-06 00:00:00+00:00
[2023-01-07T05:33:29.690+0000] {standard_task_runner.py:55} INFO - Started process 223 to run task
[2023-01-07T05:33:29.743+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'transaction_01.insert_data', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '648', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp9uc23ufo']
[2023-01-07T05:33:29.760+0000] {standard_task_runner.py:83} INFO - Job 648: Subtask transaction_01.insert_data
[2023-01-07T05:33:29.841+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T05:33:30.306+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.transaction_01.insert_data scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T05:33:30.837+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=transaction_01.insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T05:33:30.843+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-07T05:33:30.885+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-07T05:33:30.889+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-07T05:33:30.923+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-07T05:33:31.835+0000] {bigquery.py:2842} INFO - Project not included in destination_project_dataset_table: cosmetic.transaction; using project "my-kubeflow-370515"
[2023-01-07T05:33:31.839+0000] {bigquery.py:1554} INFO - Inserting job ***_1673069611837618_647f5439a545c01af290f107921986eb
[2023-01-07T05:33:34.930+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=transaction_01.insert_data, execution_date=20230106T000000, start_date=20230107T053329, end_date=20230107T053334
[2023-01-07T05:33:35.037+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T05:33:35.234+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
