[2022-12-31T23:30:53.029+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.extract manual__2022-12-31T23:30:37.791944+00:00 [queued]>
[2022-12-31T23:30:53.091+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.extract manual__2022-12-31T23:30:37.791944+00:00 [queued]>
[2022-12-31T23:30:53.093+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-31T23:30:53.095+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-31T23:30:53.096+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-31T23:30:53.194+0000] {taskinstance.py:1383} INFO - Executing <Task(ExtractOperator): transaction.extract> on 2022-12-31 23:30:37.791944+00:00
[2022-12-31T23:30:53.213+0000] {standard_task_runner.py:55} INFO - Started process 322 to run task
[2022-12-31T23:30:53.232+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'transaction.extract', 'manual__2022-12-31T23:30:37.791944+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpdkf0ioca']
[2022-12-31T23:30:53.236+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask transaction.extract
[2022-12-31T23:30:53.598+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.transaction.extract manual__2022-12-31T23:30:37.791944+00:00 [running]> on host 6bd76effbc07
[2022-12-31T23:30:54.062+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=transaction.extract
AIRFLOW_CTX_EXECUTION_DATE=2022-12-31T23:30:37.791944+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-31T23:30:37.791944+00:00
[2022-12-31T23:30:54.065+0000] {logging_mixin.py:120} INFO - transaction
[2022-12-31T23:30:54.120+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/utilties/extract_operator.py", line 28, in execute
    data=pd.DataFrame(values)
NameError: name 'values' is not defined
[2022-12-31T23:30:54.222+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dpt_cosmetic, task_id=transaction.extract, execution_date=20221231T233037, start_date=20221231T233053, end_date=20221231T233054
[2022-12-31T23:30:54.338+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 60 for task transaction.extract (name 'values' is not defined; 322)
[2022-12-31T23:30:54.371+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-31T23:30:54.531+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
