[2023-01-01T01:15:43.592+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.extract manual__2023-01-01T01:15:29.169620+00:00 [queued]>
[2023-01-01T01:15:43.666+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.extract manual__2023-01-01T01:15:29.169620+00:00 [queued]>
[2023-01-01T01:15:43.668+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T01:15:43.670+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-01T01:15:43.672+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T01:15:43.778+0000] {taskinstance.py:1383} INFO - Executing <Task(ExtractOperator): transaction.extract> on 2023-01-01 01:15:29.169620+00:00
[2023-01-01T01:15:43.800+0000] {standard_task_runner.py:55} INFO - Started process 858 to run task
[2023-01-01T01:15:43.820+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'transaction.extract', 'manual__2023-01-01T01:15:29.169620+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmplj4zxljl']
[2023-01-01T01:15:43.824+0000] {standard_task_runner.py:83} INFO - Job 128: Subtask transaction.extract
[2023-01-01T01:15:44.219+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.transaction.extract manual__2023-01-01T01:15:29.169620+00:00 [running]> on host 6bd76effbc07
[2023-01-01T01:15:44.624+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=transaction.extract
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T01:15:29.169620+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-01T01:15:29.169620+00:00
[2023-01-01T01:15:44.666+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/utilties/extract_operator.py", line 22, in execute
    csv_writer=open("./{}.csv".format(self.db_collection,'w'))
FileNotFoundError: [Errno 2] No such file or directory: './transaction.csv'
[2023-01-01T01:15:44.722+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dpt_cosmetic, task_id=transaction.extract, execution_date=20230101T011529, start_date=20230101T011543, end_date=20230101T011544
[2023-01-01T01:15:44.791+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 128 for task transaction.extract ([Errno 2] No such file or directory: './transaction.csv'; 858)
[2023-01-01T01:15:44.845+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-01T01:15:45.019+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
