[2023-01-06T00:11:26.301+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.insert_data manual__2023-01-06T00:11:10.374258+00:00 [queued]>
[2023-01-06T00:11:26.346+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.insert_data manual__2023-01-06T00:11:10.374258+00:00 [queued]>
[2023-01-06T00:11:26.347+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T00:11:26.349+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-06T00:11:26.350+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T00:11:26.421+0000] {taskinstance.py:1383} INFO - Executing <Task(GCSToBigQueryOperator): insert_data> on 2023-01-06 00:11:10.374258+00:00
[2023-01-06T00:11:26.437+0000] {standard_task_runner.py:55} INFO - Started process 152 to run task
[2023-01-06T00:11:26.452+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'insert_data', 'manual__2023-01-06T00:11:10.374258+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp9t0un9vf']
[2023-01-06T00:11:26.461+0000] {standard_task_runner.py:83} INFO - Job 329: Subtask insert_data
[2023-01-06T00:11:26.763+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.insert_data manual__2023-01-06T00:11:10.374258+00:00 [running]> on host fdf4acf1d8ed
[2023-01-06T00:11:27.102+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:11:10.374258+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T00:11:10.374258+00:00
[2023-01-06T00:11:27.108+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-06T00:11:27.147+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-06T00:11:27.153+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-06T00:11:27.177+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-06T00:11:27.863+0000] {bigquery.py:2842} INFO - Project not included in destination_project_dataset_table: cosmetic.transaction; using project "my-kubeflow-370515"
[2023-01-06T00:11:27.867+0000] {bigquery.py:1554} INFO - Inserting job ***_1672963887865761_647f5439a545c01af290f107921986eb
[2023-01-06T00:11:32.553+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=insert_data, execution_date=20230106T001110, start_date=20230106T001126, end_date=20230106T001132
[2023-01-06T00:11:32.643+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-06T00:11:32.744+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
