[2023-01-06T01:57:41.039+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction_01.create_table manual__2023-01-06T01:57:35.165428+00:00 [queued]>
[2023-01-06T01:57:41.056+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction_01.create_table manual__2023-01-06T01:57:35.165428+00:00 [queued]>
[2023-01-06T01:57:41.056+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T01:57:41.057+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-06T01:57:41.057+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T01:57:41.078+0000] {taskinstance.py:1383} INFO - Executing <Task(BigQueryCreateEmptyTableOperator): transaction_01.create_table> on 2023-01-06 01:57:35.165428+00:00
[2023-01-06T01:57:41.085+0000] {standard_task_runner.py:55} INFO - Started process 129 to run task
[2023-01-06T01:57:41.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'transaction_01.create_table', 'manual__2023-01-06T01:57:35.165428+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpuij6p8vi']
[2023-01-06T01:57:41.092+0000] {standard_task_runner.py:83} INFO - Job 355: Subtask transaction_01.create_table
[2023-01-06T01:57:41.181+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.transaction_01.create_table manual__2023-01-06T01:57:35.165428+00:00 [running]> on host fdf4acf1d8ed
[2023-01-06T01:57:41.278+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=transaction_01.create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T01:57:35.165428+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T01:57:35.165428+00:00
[2023-01-06T01:57:41.280+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-06T01:57:41.290+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-06T01:57:41.291+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-06T01:57:41.299+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-06T01:57:41.858+0000] {bigquery.py:910} INFO - Creating table
[2023-01-06T01:57:42.453+0000] {bigquery.py:926} INFO - Table my-kubeflow-370515.cosmetic.transaction_01 created successfully
[2023-01-06T01:57:42.491+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=transaction_01.create_table, execution_date=20230106T015735, start_date=20230106T015741, end_date=20230106T015742
[2023-01-06T01:57:42.549+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-06T01:57:42.599+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
