[2023-01-02T15:49:20.429+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.transform manual__2023-01-02T15:49:07.908072+00:00 [queued]>
[2023-01-02T15:49:20.479+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.transform manual__2023-01-02T15:49:07.908072+00:00 [queued]>
[2023-01-02T15:49:20.481+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T15:49:20.482+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-02T15:49:20.483+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T15:49:20.564+0000] {taskinstance.py:1383} INFO - Executing <Task(TransformOperator): transaction.transform> on 2023-01-02 15:49:07.908072+00:00
[2023-01-02T15:49:20.580+0000] {standard_task_runner.py:55} INFO - Started process 136 to run task
[2023-01-02T15:49:20.599+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'transaction.transform', 'manual__2023-01-02T15:49:07.908072+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpqgstuy_2']
[2023-01-02T15:49:20.603+0000] {standard_task_runner.py:83} INFO - Job 215: Subtask transaction.transform
[2023-01-02T15:49:20.941+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.transaction.transform manual__2023-01-02T15:49:07.908072+00:00 [running]> on host 703acec1b71e
[2023-01-02T15:49:21.335+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=transaction.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T15:49:07.908072+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T15:49:07.908072+00:00
[2023-01-02T15:49:31.491+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

[2023-01-02T15:49:34.088+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/utilties/operator.py", line 85, in execute
    self.save_to_local(df)
TypeError: save_to_local() missing 1 required positional argument: 'data'
[2023-01-02T15:49:34.126+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dpt_cosmetic, task_id=transaction.transform, execution_date=20230102T154907, start_date=20230102T154920, end_date=20230102T154934
[2023-01-02T15:49:34.187+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 215 for task transaction.transform (save_to_local() missing 1 required positional argument: 'data'; 136)
[2023-01-02T15:49:34.253+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-02T15:49:34.341+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
