[2023-01-07T04:46:36.363+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bq_process.product_stats.create_table manual__2023-01-07T04:46:16.333150+00:00 [queued]>
[2023-01-07T04:46:36.508+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bq_process.product_stats.create_table manual__2023-01-07T04:46:16.333150+00:00 [queued]>
[2023-01-07T04:46:36.512+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T04:46:36.516+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T04:46:36.532+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T04:46:36.792+0000] {taskinstance.py:1383} INFO - Executing <Task(BigQueryCreateEmptyTableOperator): product_stats.create_table> on 2023-01-07 04:46:16.333150+00:00
[2023-01-07T04:46:36.856+0000] {standard_task_runner.py:55} INFO - Started process 280 to run task
[2023-01-07T04:46:36.976+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bq_process', 'product_stats.create_table', 'manual__2023-01-07T04:46:16.333150+00:00', '--job-id', '521', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_dag.py', '--cfg-path', '/tmp/tmpuku05dj0']
[2023-01-07T04:46:36.995+0000] {standard_task_runner.py:83} INFO - Job 521: Subtask product_stats.create_table
[2023-01-07T04:46:37.624+0000] {task_command.py:376} INFO - Running <TaskInstance: bq_process.product_stats.create_table manual__2023-01-07T04:46:16.333150+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T04:46:38.822+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bq_process
AIRFLOW_CTX_TASK_ID=product_stats.create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-07T04:46:16.333150+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-07T04:46:16.333150+00:00
[2023-01-07T04:46:38.835+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-07T04:46:38.919+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-07T04:46:38.946+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-07T04:46:39.004+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-07T04:46:40.045+0000] {bigquery.py:910} INFO - Creating table
[2023-01-07T04:46:41.089+0000] {bigquery.py:926} INFO - Table my-kubeflow-370515.cosmetic.product_stats created successfully
[2023-01-07T04:46:41.174+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=bq_process, task_id=product_stats.create_table, execution_date=20230107T044616, start_date=20230107T044636, end_date=20230107T044641
[2023-01-07T04:46:41.304+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T04:46:41.595+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
