[2023-01-07T01:57:10.918+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T01:57:11.081+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T01:57:11.083+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T01:57:11.084+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T01:57:11.085+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T01:57:11.284+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): product.transform> on 2023-01-06 00:00:00+00:00
[2023-01-07T01:57:11.354+0000] {standard_task_runner.py:55} INFO - Started process 118 to run task
[2023-01-07T01:57:11.387+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'product.transform', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpuu7oewr8']
[2023-01-07T01:57:11.407+0000] {standard_task_runner.py:83} INFO - Job 473: Subtask product.transform
[2023-01-07T01:57:11.534+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T01:57:12.244+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T01:57:13.872+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=product.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T01:57:13.888+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-07T01:57:13.929+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 1']
[2023-01-07T01:57:14.116+0000] {subprocess.py:86} INFO - Output:
[2023-01-07T01:57:15.140+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-01-07T01:57:15.801+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=product.transform, execution_date=20230106T000000, start_date=20230107T015710, end_date=20230107T015715
[2023-01-07T01:57:16.940+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T01:57:18.685+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-07T05:16:28.141+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:16:28.539+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:16:28.578+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:16:28.588+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T05:16:28.598+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:16:28.869+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): product.transform> on 2023-01-06 00:00:00+00:00
[2023-01-07T05:16:28.952+0000] {standard_task_runner.py:55} INFO - Started process 420 to run task
[2023-01-07T05:16:29.094+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'product.transform', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '559', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp51hrjkz4']
[2023-01-07T05:16:29.133+0000] {standard_task_runner.py:83} INFO - Job 559: Subtask product.transform
[2023-01-07T05:16:29.384+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T05:16:30.442+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T05:16:52.301+0000] {base_job.py:232} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 204, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2961, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3039, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2775, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2878, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-01-07T05:18:03.182+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=product.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T05:18:03.745+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-07T05:18:03.755+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 1']
[2023-01-07T05:18:04.351+0000] {subprocess.py:86} INFO - Output:
[2023-01-07T05:18:05.536+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-01-07T05:18:06.749+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=product.transform, execution_date=20230106T000000, start_date=20230107T051628, end_date=20230107T051806
[2023-01-07T05:18:08.291+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T05:18:09.908+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-07T05:32:16.104+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:32:16.174+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-07T05:32:16.176+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:32:16.177+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T05:32:16.178+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:32:16.393+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): product.transform> on 2023-01-06 00:00:00+00:00
[2023-01-07T05:32:16.497+0000] {standard_task_runner.py:55} INFO - Started process 91 to run task
[2023-01-07T05:32:16.524+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'product.transform', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp6e1ns3m8']
[2023-01-07T05:32:16.577+0000] {standard_task_runner.py:83} INFO - Job 613: Subtask product.transform
[2023-01-07T05:32:16.716+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-07T05:32:17.299+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.product.transform scheduled__2023-01-06T00:00:00+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T05:32:18.260+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=product.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-07T05:32:18.267+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-07T05:32:18.279+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 1']
[2023-01-07T05:32:18.393+0000] {subprocess.py:86} INFO - Output:
[2023-01-07T05:32:19.432+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-01-07T05:32:19.817+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=product.transform, execution_date=20230106T000000, start_date=20230107T053216, end_date=20230107T053219
[2023-01-07T05:32:20.631+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-07T05:32:21.025+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
